spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8765

#management:
#  endpoint:
#    gateway:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
